# SPDX-FileCopyrightText: 2026 maplike contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = [".", "maplike_derive"]

[package]
name = "maplike"
version = "0.13.4"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Rust traits for abstract containers and operations over them."
repository = "https://github.com/mikwielgus/maplike"
documentation = "https://docs.rs/maplike"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["container", "undo", "redo", "rtree", "no_std"]
categories = ["data-structures", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]

## Enables the `Container` and `Assign` derive macros.
derive = ["dep:maplike_derive"]

## Disable for `no_std` compatibility. Implies `alloc`.
std = ["alloc"]

## Enables convenience implementations for `alloc` collections (`BTreeMap`,
## `BTreeSet`, `Vec`, `VecDeque`).
alloc = []

## Enables convenience implementations for `arrayvec::ArrayVec` and
## `arrayvec::ArrayString`.
arrayvec = ["dep:arrayvec"]

## Enables convenience implementations for `bidimap::BiBTreeMap` and,
## additionally under the `std` feature, `bidimap::BiHashMap`.
bidimap = ["dep:bidimap"]

## Enables convenience implementations for `indexmap::IndexMap` and
## `indexmap::IndexSet`.
indexmap = ["dep:indexmap"]

## Enables convenience implementations for `rstar::RTree`.
rstar = ["dep:rstar"]

## Enables convenience implementations for `stable_vec::StableVec`.
stable-vec = ["dep:stable-vec"]

## Enables convenience implementations for `thunderdome::Arena`.
thunderdome = ["dep:thunderdome"]

## Enables convenience implementations for `smallvec::SmallVec`.
smallvec = ["dep:smallvec"]

## Enables convenience implementations for `tinyvec::ArrayVec` and
## `tinyvec::TinyVec`.
tinyvec = ["dep:tinyvec"]

## Enables `serde` support. Derives `Serialize` and `Deserialize` traits for
## `One`.
serde = ["dep:serde"]

[dependencies]
maplike_derive = { version = "0.13", optional = true, path = "maplike_derive" }
arrayvec = { version = "0.7", optional = true }
bidimap = { version = "0.7", optional = true }
document-features = { version = "0.2", optional = true }
indexmap = { version = "2.14", optional = true }
rstar = { version = ">= 0.12, < 0.14", optional = true }
smallvec = { version = "1", optional = true }
stable-vec = { version = "0.4", optional = true }
thunderdome = { version = "0.6", optional = true }
tinyvec = { version = "1", features = ["alloc"], optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive", "alloc"] }

[dev-dependencies]
indexmap = "2.14"
stable-vec = "0.4"
thunderdome = "0.6"
rstar = ">= 0.12, < 0.14"
smallvec = "1"
arrayvec = "0.7"
tinyvec = { version = "1", features = ["alloc"] }

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]
